# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-18 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.CharField(max_length=15)),
                ('companyid', models.CharField(max_length=15)),
                ('dc', models.CharField(blank=True, max_length=15, null=True)),
                ('ca_acct', models.CharField(blank=True, max_length=15, null=True)),
                ('main_acct', models.CharField(blank=True, max_length=15, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=15, null=True)),
                ('ca_formulary', models.CharField(blank=True, max_length=15, null=True)),
                ('mus_formulary', models.CharField(blank=True, max_length=15, null=True)),
                ('alternate_items', models.CharField(blank=True, max_length=15, null=True)),
                ('utilization', models.CharField(blank=True, max_length=15, null=True)),
                ('refill_line_utilization', models.CharField(blank=True, max_length=15, null=True)),
                ('ca_doses_dispensed', models.CharField(blank=True, max_length=15, null=True)),
                ('non_ca_doses_dispensed', models.CharField(blank=True, max_length=15, null=True)),
                ('total_doses_dispenses', models.CharField(blank=True, max_length=15, null=True)),
                ('total_refills', models.CharField(blank=True, max_length=15, null=True)),
                ('ca_lines_refilled', models.CharField(blank=True, max_length=15, null=True)),
                ('non_ca_lines_refilled', models.CharField(blank=True, max_length=15, null=True)),
                ('ca_vend_to_refill_ratio', models.CharField(blank=True, max_length=15, null=True)),
                ('non_ca_vend_to_refill_ratio', models.CharField(blank=True, max_length=15, null=True)),
                ('total_vend_refill_ratio', models.CharField(blank=True, max_length=15, null=True)),
                ('non_ca_stock_outs', models.CharField(blank=True, max_length=15, null=True)),
                ('ca_stock_outs', models.CharField(blank=True, max_length=15, null=True)),
                ('total_stock_outs', models.CharField(blank=True, max_length=15, null=True)),
                ('total_stock_outs_per_100_dispenses', models.CharField(blank=True, max_length=15, null=True)),
                ('totalmedstation', models.CharField(blank=True, max_length=15, null=True)),
                ('blockedmedstation', models.CharField(blank=True, max_length=15, null=True)),
                ('activemedstation', models.CharField(blank=True, max_length=15, null=True)),
                ('ineligible_items', models.CharField(blank=True, max_length=15, null=True)),
                ('ca_scan_qty', models.CharField(blank=True, max_length=15, null=True)),
                ('ca_refill_qty', models.CharField(blank=True, max_length=15, null=True)),
                ('ca_scan_rate', models.CharField(blank=True, max_length=15, null=True)),
                ('non_ca_scan_qty', models.CharField(blank=True, max_length=15, null=True)),
                ('non_ca_refill_qty', models.CharField(blank=True, max_length=15, null=True)),
                ('non_ca_scan_rate', models.CharField(blank=True, max_length=15, null=True)),
                ('total_scan_qty', models.CharField(blank=True, max_length=15, null=True)),
                ('total_refill_qty', models.CharField(blank=True, max_length=15, null=True)),
                ('totalscanrate', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
