# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-18 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='report_date',
            field=models.DateField(),
        ),
    ]
